-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 08:45:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rainbow_Six_Siege
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rainbow_Six_Siege
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Rainbow_Six_Siege` DEFAULT CHARACTER SET utf8 ;
USE `Rainbow_Six_Siege` ;

-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Entrenador` (
  `idEntrenador` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEntrenador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Habilidad` (
  `idHabilidad` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabilidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Arma` (
  `idArma` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Capacidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Personaje` (
  `idPersonaje` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  `Habilidad_idHabilidad` INT NOT NULL,
  `Arma_idArma` INT NOT NULL,
  PRIMARY KEY (`idPersonaje`, `Habilidad_idHabilidad`, `Arma_idArma`),
  INDEX `fk_Personaje_Habilidad1_idx` (`Habilidad_idHabilidad` ASC),
  INDEX `fk_Personaje_Arma1_idx` (`Arma_idArma` ASC),
  CONSTRAINT `fk_Personaje_Habilidad1`
    FOREIGN KEY (`Habilidad_idHabilidad`)
    REFERENCES `Rainbow_Six_Siege`.`Habilidad` (`idHabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_Arma1`
    FOREIGN KEY (`Arma_idArma`)
    REFERENCES `Rainbow_Six_Siege`.`Arma` (`idArma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Jugador` (
  `idJugador` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Personaje_idPersonaje` INT NOT NULL,
  PRIMARY KEY (`idJugador`, `Personaje_idPersonaje`),
  INDEX `fk_Jugador_Personaje1_idx` (`Personaje_idPersonaje` ASC),
  CONSTRAINT `fk_Jugador_Personaje1`
    FOREIGN KEY (`Personaje_idPersonaje`)
    REFERENCES `Rainbow_Six_Siege`.`Personaje` (`idPersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Equipo` (
  `idEquipo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Entrenador_idEntrenador` INT NOT NULL,
  `Jugador_idJugador` INT NOT NULL,
  PRIMARY KEY (`idEquipo`, `Entrenador_idEntrenador`, `Jugador_idJugador`),
  INDEX `fk_Equipo_Entrenador1_idx` (`Entrenador_idEntrenador` ASC),
  INDEX `fk_Equipo_Jugador1_idx` (`Jugador_idJugador` ASC),
  CONSTRAINT `fk_Equipo_Entrenador1`
    FOREIGN KEY (`Entrenador_idEntrenador`)
    REFERENCES `Rainbow_Six_Siege`.`Entrenador` (`idEntrenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Jugador1`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `Rainbow_Six_Siege`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rainbow_Six_Siege`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rainbow_Six_Siege`.`Partidos` (
  `idPartidos` INT NOT NULL,
  `Marcador` VARCHAR(45) NOT NULL,
  `Mapa` VARCHAR(45) NOT NULL,
  `Equipo_idEquipo` INT NOT NULL,
  `Equipo_idEquipo1` INT NOT NULL,
  PRIMARY KEY (`idPartidos`, `Equipo_idEquipo`, `Equipo_idEquipo1`),
  INDEX `fk_Partidos_Equipo1_idx` (`Equipo_idEquipo` ASC),
  INDEX `fk_Partidos_Equipo2_idx` (`Equipo_idEquipo1` ASC),
  CONSTRAINT `fk_Partidos_Equipo1`
    FOREIGN KEY (`Equipo_idEquipo`)
    REFERENCES `Rainbow_Six_Siege`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_Equipo2`
    FOREIGN KEY (`Equipo_idEquipo1`)
    REFERENCES `Rainbow_Six_Siege`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
	